<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CoreAuto.Examples</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FullIntegrationIngress.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../cawbs/DotNet/CoreAuto.Cawbs.csproj" />
    <ProjectReference Include="../../transform/DotNet/CoreAuto.Transform.csproj" />
    <ProjectReference Include="../../files/DotNet/CoreAuto.Files.csproj" />
    <ProjectReference Include="../../queues/kafka/DotNet/CoreAuto.Kafka.csproj" />
  </ItemGroup>
</Project>
